/*
 * gimbal_tasks.h
 *
 *  Created on: Jun 24, 2019
 *      Author: ntron
 */

#ifndef GIMBAL_H_
#define GIMBAL_H_

/* The idea of this module (header/source) is that it will contain the
 * entire structure of the gimbal application.
 *
 * Main only has to:
 * 		- Call all peripheral init functions (generated by CubeMX)
 * 		- Call the init functions in here
 * 		- Start the FreeRTOS scheduler
 */

/* ================== INIT FUNCTIONS ===================== */
/// Top-level Init function
void Gimbal_Init(void);

/// Init the peripheral sensor modules
void Gimbal_InitSensors(void);

/// Init the tasks
void Gimbal_InitTasks(void);

/* ================== TASK FUNCTIONS ===================== */
/// IMU interrupt handler
void vImuIRQHandler(void* pvParameters);

/// Handler for UART receive interrupt
void vUartRxIRQHandler(void* pvParameters);

/// Primary Gimbal Control Loop
void vGimbalControlLoopTask(void* pvParameters);
/// others...

/* ============= HAL IRQ HANDLER CALLBACKS =============== */
/// defined in the source file, declared in various system headers

#endif /* GIMBAL_H_ */
